[project]
name = "gemini-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.17.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
gemini-chat = "gemini_chat:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
